Repository VM-Chinese-translate-group/MC-Eternal, pull requests merged in 2023-01, with the labels that each got.

#9 添加moartinkers模组
  资源包/assets/moartinkers/lang/en_us.lang
Labels: ready to merge

#21 更新splashes.txt
  resources/assets/splashes.txt
Labels: approve, ready to merge

#15 新增illagers+模组汉化
  资源包/assets/illagers_plus/lang/de_de.lang
  资源包/assets/illagers_plus/lang/en_us.lang
  资源包/assets/illagers_plus/lang/zh_cn.lang
Labels: ready to merge

#19 月球章节完成
  config/ftbquests/normal/chapters/2c343c21/09a0a484.snbt
  config/ftbquests/normal/chapters/2c343c21/0bbfe38a.snbt
  config/ftbquests/normal/chapters/2c343c21/0f2bca7e.snbt
  config/ftbquests/normal/chapters/2c343c21/2b45993e.snbt
  config/ftbquests/normal/chapters/2c343c21/6995abe7.snbt
  config/ftbquests/normal/chapters/2c343c21/6a5afb68.snbt
  config/ftbquests/normal/chapters/2c343c21/6cec2eba.snbt
  config/ftbquests/normal/chapters/2c343c21/843f9376.snbt
  config/ftbquests/normal/chapters/2c343c21/8b8327cb.snbt
  config/ftbquests/normal/chapters/2c343c21/9a6c0406.snbt
  config/ftbquests/normal/chapters/2c343c21/9c87f669.snbt
  config/ftbquests/normal/chapters/2c343c21/a69ad6b4.snbt
  config/ftbquests/normal/chapters/2c343c21/b9fe6825.snbt
  config/ftbquests/normal/chapters/2c343c21/bf926dd4.snbt
  config/ftbquests/normal/chapters/2c343c21/cde158a5.snbt
  config/ftbquests/normal/chapters/2c343c21/chapter.snbt
  config/ftbquests/normal/chapters/2c343c21/ddb8ee34.snbt
  config/ftbquests/normal/chapters/2c343c21/e5dcb3a5.snbt
  config/ftbquests/normal/chapters/2c343c21/f585cb3b.snbt
  config/ftbquests/normal/chapters/2c343c21/fa71216c.snbt
  config/ftbquests/normal/chapters/2c343c21/ff9e45c6.snbt
Labels: ready to merge

#30 高级火箭汉化
  config/ftbquests/classic/chapters/92b211dd/0374614c.snbt
  config/ftbquests/classic/chapters/92b211dd/0479a7a1.snbt
  config/ftbquests/classic/chapters/92b211dd/091e6c54.snbt
  config/ftbquests/classic/chapters/92b211dd/14caadfa.snbt
  config/ftbquests/classic/chapters/92b211dd/1781981e.snbt
  config/ftbquests/classic/chapters/92b211dd/28e9bc60.snbt
  config/ftbquests/classic/chapters/92b211dd/39f14c3e.snbt
  config/ftbquests/classic/chapters/92b211dd/3f406a26.snbt
  config/ftbquests/classic/chapters/92b211dd/40210c1c.snbt
  config/ftbquests/classic/chapters/92b211dd/604d9e61.snbt
  config/ftbquests/classic/chapters/92b211dd/619385a7.snbt
  config/ftbquests/classic/chapters/92b211dd/74150491.snbt
  config/ftbquests/classic/chapters/92b211dd/7a35fec9.snbt
  config/ftbquests/classic/chapters/92b211dd/a1869f6a.snbt
  config/ftbquests/classic/chapters/92b211dd/a4168e42.snbt
  config/ftbquests/classic/chapters/92b211dd/ac91846c.snbt
  config/ftbquests/classic/chapters/92b211dd/bb9f8d30.snbt
  config/ftbquests/classic/chapters/92b211dd/c2a800d8.snbt
  config/ftbquests/classic/chapters/92b211dd/chapter.snbt
  config/ftbquests/classic/chapters/92b211dd/d5dbf68e.snbt
  config/ftbquests/classic/chapters/92b211dd/d78bfda8.snbt
  config/ftbquests/classic/chapters/92b211dd/db9592f2.snbt
  config/ftbquests/normal/chapters/92b211dd/0374614c.snbt
  config/ftbquests/normal/chapters/92b211dd/0479a7a1.snbt
  config/ftbquests/normal/chapters/92b211dd/091e6c54.snbt
  config/ftbquests/normal/chapters/92b211dd/14caadfa.snbt
  config/ftbquests/normal/chapters/92b211dd/1781981e.snbt
  config/ftbquests/normal/chapters/92b211dd/28e9bc60.snbt
  config/ftbquests/normal/chapters/92b211dd/39f14c3e.snbt
  config/ftbquests/normal/chapters/92b211dd/3f406a26.snbt
  config/ftbquests/normal/chapters/92b211dd/40210c1c.snbt
  config/ftbquests/normal/chapters/92b211dd/604d9e61.snbt
  config/ftbquests/normal/chapters/92b211dd/619385a7.snbt
  config/ftbquests/normal/chapters/92b211dd/74150491.snbt
  config/ftbquests/normal/chapters/92b211dd/7a35fec9.snbt
  config/ftbquests/normal/chapters/92b211dd/a1869f6a.snbt
  config/ftbquests/normal/chapters/92b211dd/a4168e42.snbt
  config/ftbquests/normal/chapters/92b211dd/ac91846c.snbt
  config/ftbquests/normal/chapters/92b211dd/bb9f8d30.snbt
  config/ftbquests/normal/chapters/92b211dd/c2a800d8.snbt
  config/ftbquests/normal/chapters/92b211dd/chapter.snbt
  config/ftbquests/normal/chapters/92b211dd/d5dbf68e.snbt
  config/ftbquests/normal/chapters/92b211dd/d78bfda8.snbt
  config/ftbquests/normal/chapters/92b211dd/db9592f2.snbt
Labels: ready to merge

#20 贪婪
  config/ftbquests/classic/chapters/99cbbc10/0202e33e.snbt
  config/ftbquests/classic/chapters/99cbbc10/0331ef03.snbt
  config/ftbquests/classic/chapters/99cbbc10/08eabb62.snbt
  config/ftbquests/classic/chapters/99cbbc10/0a5005e1.snbt
  config/ftbquests/classic/chapters/99cbbc10/17f50c84.snbt
  config/ftbquests/classic/chapters/99cbbc10/1bc69a3a.snbt
  config/ftbquests/classic/chapters/99cbbc10/2279e501.snbt
  config/ftbquests/classic/chapters/99cbbc10/24c36876.snbt
  config/ftbquests/classic/chapters/99cbbc10/30d452fc.snbt
  config/ftbquests/classic/chapters/99cbbc10/49a61cc5.snbt
  config/ftbquests/classic/chapters/99cbbc10/4e1d444f.snbt
  config/ftbquests/classic/chapters/99cbbc10/4e2405c8.snbt
  config/ftbquests/classic/chapters/99cbbc10/4ea88333.snbt
  config/ftbquests/classic/chapters/99cbbc10/4ff39518.snbt
  config/ftbquests/classic/chapters/99cbbc10/5aaf295b.snbt
  config/ftbquests/classic/chapters/99cbbc10/60b7d71a.snbt
  config/ftbquests/classic/chapters/99cbbc10/68ad9abc.snbt
  config/ftbquests/classic/chapters/99cbbc10/77c8ccf2.snbt
  config/ftbquests/classic/chapters/99cbbc10/7a3c190f.snbt
  config/ftbquests/classic/chapters/99cbbc10/7fe7ff02.snbt
  config/ftbquests/classic/chapters/99cbbc10/8912de99.snbt
  config/ftbquests/classic/chapters/99cbbc10/8afb2484.snbt
  config/ftbquests/classic/chapters/99cbbc10/92b82a90.snbt
  config/ftbquests/classic/chapters/99cbbc10/9d42bba7.snbt
  config/ftbquests/classic/chapters/99cbbc10/a280b41d.snbt
  config/ftbquests/classic/chapters/99cbbc10/ac376b3e.snbt
  config/ftbquests/classic/chapters/99cbbc10/b06519f8.snbt
  config/ftbquests/classic/chapters/99cbbc10/b5b78d4f.snbt
  config/ftbquests/classic/chapters/99cbbc10/b81e2106.snbt
  config/ftbquests/classic/chapters/99cbbc10/c27c3ded.snbt
  config/ftbquests/classic/chapters/99cbbc10/c44a066c.snbt
  config/ftbquests/classic/chapters/99cbbc10/c5615663.snbt
  config/ftbquests/classic/chapters/99cbbc10/cabdc932.snbt
  config/ftbquests/classic/chapters/99cbbc10/cb9faa4a.snbt
  config/ftbquests/classic/chapters/99cbbc10/cf6099d1.snbt
  config/ftbquests/classic/chapters/99cbbc10/chapter.snbt
  config/ftbquests/classic/chapters/99cbbc10/d58c55f1.snbt
  config/ftbquests/classic/chapters/99cbbc10/dd50e960.snbt
  config/ftbquests/classic/chapters/99cbbc10/ea52fe16.snbt
  config/ftbquests/classic/chapters/99cbbc10/ec7b14aa.snbt
Labels: ready to merge

#34 reward table汉化提交
  config/ftbquests/normal/reward_tables/0bfc8487.snbt
  config/ftbquests/normal/reward_tables/0cfb5327.snbt
  config/ftbquests/normal/reward_tables/0fae6112.snbt
  config/ftbquests/normal/reward_tables/12543304.snbt
  config/ftbquests/normal/reward_tables/1425b69a.snbt
  config/ftbquests/normal/reward_tables/1ac1ad5d.snbt
  config/ftbquests/normal/reward_tables/1eb6fea9.snbt
  config/ftbquests/normal/reward_tables/34217fe6.snbt
  config/ftbquests/normal/reward_tables/35dbf7dd.snbt
  config/ftbquests/normal/reward_tables/39ee3421.snbt
  config/ftbquests/normal/reward_tables/4a1cdbe2.snbt
  config/ftbquests/normal/reward_tables/666c6c47.snbt
  config/ftbquests/normal/reward_tables/6b151f49.snbt
  config/ftbquests/normal/reward_tables/7009a3fa.snbt
  config/ftbquests/normal/reward_tables/7a917c94.snbt
  config/ftbquests/normal/reward_tables/7e2222fe.snbt
  config/ftbquests/normal/reward_tables/861e9585.snbt
  config/ftbquests/normal/reward_tables/8e152c32.snbt
  config/ftbquests/normal/reward_tables/93e32f26.snbt
  config/ftbquests/normal/reward_tables/95382cf1.snbt
  config/ftbquests/normal/reward_tables/bfdd5e7d.snbt
  config/ftbquests/normal/reward_tables/c95f850e.snbt
  config/ftbquests/normal/reward_tables/dad26af0.snbt
  config/ftbquests/normal/reward_tables/dda2118b.snbt
  config/ftbquests/normal/reward_tables/e655ed34.snbt
  config/ftbquests/normal/reward_tables/f02f3552.snbt
  config/ftbquests/normal/reward_tables/f22bcefe.snbt
  config/ftbquests/normal/reward_tables/f5768b6f.snbt
Labels: ready to merge

#37 更新漏译
  config/ftbquests/classic/chapters/8f571a77/1367cd5d.snbt
  config/ftbquests/classic/chapters/8f571a77/19c7c06f.snbt
  config/ftbquests/classic/chapters/8f571a77/2722c20b.snbt
  config/ftbquests/classic/chapters/8f571a77/36cc72e8.snbt
  config/ftbquests/classic/chapters/8f571a77/45b102f9.snbt
  config/ftbquests/classic/chapters/8f571a77/4dd1844a.snbt
  config/ftbquests/classic/chapters/8f571a77/97a98591.snbt
  config/ftbquests/classic/chapters/8f571a77/97e53a17.snbt
  config/ftbquests/classic/chapters/8f571a77/cb3bf98e.snbt
  config/ftbquests/normal/chapters/8f571a77/1367cd5d.snbt
  config/ftbquests/normal/chapters/8f571a77/19c7c06f.snbt
  config/ftbquests/normal/chapters/8f571a77/2722c20b.snbt
  config/ftbquests/normal/chapters/8f571a77/36cc72e8.snbt
  config/ftbquests/normal/chapters/8f571a77/45b102f9.snbt
  config/ftbquests/normal/chapters/8f571a77/4dd1844a.snbt
  config/ftbquests/normal/chapters/8f571a77/97a98591.snbt
  config/ftbquests/normal/chapters/8f571a77/97e53a17.snbt
  config/ftbquests/normal/chapters/8f571a77/cb3bf98e.snbt
Labels: ready to merge, size/M
